[theme]
# Primary accent color for interactive elements.
primaryColor="#007bff"  # A common, pleasant blue. You can change this.

# Background color for the main content area.
backgroundColor="#F0F2F6" # A light grey, often good for dashboards.

# Background color for sidebar and most other UI elements.
secondaryBackgroundColor="#FFFFFF" # White for a clean look.

# Text color for the main content area.
textColor="#212529" # A dark grey, good for readability.

# Font family for all text in the app.
# Options: "sans serif", "serif", "monospace"
font="sans serif"

[logger]
# Level for Streamlit's own logger.
# Options: "error", "warning", "info", "debug"
# This is separate from your application's logger configured in src/config.py
level = "info"

[server]
# Port the server will listen on. Defaults to 8501.
# port = 8501

# If true, will attempt to open a browser window on start.
# browser.serverAddress = "localhost"
# browser.gatherUsageStats = true # Set to false to disable sending usage stats to Streamlit
# browser.serverPort = 8501

# To run headless (e.g., in a container without a browser automatically opening)
# headless = true

# To enable Cross-Origin Resource Sharing (CORS) - usually not needed for local dev
# enableCORS = false

[client]
# If true, show a warning when a DataFrame has more than 200k rows.
# Changed to a higher limit as e-commerce data can be large.
# You can adjust this based on performance.
showWarningOnDirectExecution = true
# maxCachedStats = 1000 # Default, controls stats caching

[global]
# Disable a warning about st.pyplot() global use. Not directly relevant here but common.
# deprecation.showPyplotGlobalUse = false